djmysite/blog/urls.py
from django.conf.urls import url
from .feeds import LatestPostsFeed
from . import views

urlpatterns = [
    # post views
    url(r'^$', views.post_list, name='post_list'),
    #  url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$',
        views.post_share,
        name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$',
        views.post_list,
        name='post_list_by_tag'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
    url(r'^search/$', views.post_search, name='post_search'),
]

djmysite/djmysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSiteMap

sitemaps = {'posts': PostSiteMap}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # blog urls
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'sitemap\.xml$',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemap.views.sitemap'),
]

djmysite/blog/models.py
# django imports
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
# 3rd party imports
from taggit.managers import TaggableManager

# Create your models here.


class PublishedManager(models.Manager):
    """
    gets posts with 'published' status
    """

    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(
                status='published')


class Post(models.Model):
    """
    single blog post model
    """

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=254)
    slug = models.SlugField(max_length=254, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        """
        :returns canonical URL for Post object
        """
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])

    def __str__(self):
        return self.title


class Comment(models.Model):
    """
    Model class for post Comment
    """
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

djmysite/blog/forms.py
# django imports
from django import forms
# my imports
from .models import Comment


class EmailPostForm(forms.Form):
    """
    Class for sharing posts through email with users
    """
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    """
    ModelForm for comments under the post
    """
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    """
    Class form for search queries
    """
    query = forms.CharField()

djmysite/blog/views.py
# djanog imports
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
# 3rd party imports
from taggit.views import Tag
from haystack.query import SearchQuerySet
# my imports
from .forms import EmailPostForm, CommentForm, SearchForm
from .models import Post

# Create your views here.


def post_share(request, post_id):
    # get post by id:
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # form submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())

            # "$User ($user@user) recommends you reading "$title"
            subject = '{} ({}) recommends you reading "{}"'.format(
                    cleaned_data['name'],
                    cleaned_data['email'],
                    post.title)
            # "Read "$title" at $url \n\n $User's comments: $comment
            message = 'Read "{}" at {}\n\n{}\'s comments:\n {}'.format(
                    post.title,
                    post_url,
                    cleaned_data['name'],
                    cleaned_data['comments'])
            send_mail(subject, message, 'admin@blog.com', [cleaned_data['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tags': tag})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # list of active comments goes here:
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        # comment posted
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            # Assign post to comment first!!
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            # Now Save
            new_comment.save()
    else:
        comment_form = CommentForm()

    # list of similar posts based on tag count
    post_tags_id = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_id).exclude(
            id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by(
            '-same_tags', '-publish')[:4]

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_search(request):
    form = SearchForm()
    context = {'form': form}

    if 'query' in request.GET:
        form = SearchForm(request.GET)

        if form.is_valid():
            clean_data = form.cleaned_data
            results = SearchQuerySet().models(Post).filter(
                                        content=clean_data['query']).load_all()
            total_results = results.count()
            context = {
                'form': form,
                'clean_data': clean_data,
                'results': results,
                'total_results': total_results
            }

    return render(request, 'blog/post/search.html', context)

djmysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock title %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock content %}
  </div>
  <div id="sidebar">
    <h2>Custom Blog Site</h2>
    <p>Welcome to my Custom Blog Site. We currently host {% total_posts %} posts</p>
    <p><a href="{% url 'blog:post_feed' %}">Subscribe to RSS channel</a> </p>

    <h3>Latest Posts</h3>
    {% show_latest_posts 3 %}
    <h3>Most commented Posts</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
      {% for post in most_commented_posts %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
      {% endfor %}
    </ul>

  </div>

</body>
</html>

djmysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  <p class="tags">Tags:
        {% for tag in post.tags.all %}
          <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
          </a>
          {% if not forloop.last %}, {% endif %}
        {% endfor %}
      </p>
  {{ post.body|markdown }}
  <p>
    <a href="{% url "blog:post_share" post.id %}">Share Post</a> |
    <a href="{% url "blog:post_list" %}">Get Back</a>
  </p>
  {% with comments.count as total_comments %}
    {{ total_comments }} comment{{ total_comments|pluralize }}
  {% endwith %}

  <h2>Similar posts</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
    There are no similar posts.
  {% endfor %}


  {% for comment in comments  %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
    {% empty %}
    <p> There are no comments.</p>
  {% endfor %}

  {% if new_comment %}
    <h2>Comment added.</h2>
  {% else %}
    <h2>Add a comment</h2>
    <form action="." method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Add comment"></p>
    </form>
  {% endif %}

{% endblock content %}

djmysite/blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

djmysite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Custom Blog Site{% endblock title %}

{% block content %}
  <h1>Custom Blog</h1>
  {% if tag %}
    <h2>Posts with tag "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
      {{ post.title }}
      </a>
      <p class="tags">Tags:
        {% for tag in post.tags.all %}
          <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
          </a>
          {% if not forloop.last %}, {% endif %}
        {% endfor %}
      </p>
    </h2>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  {% include 'blog/post/pagination.html' with page=posts %}
{% endblock content %}

djmysite/blog/templates/blog/post/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Prev</a>
    {% endif %}
  <span class="current">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
  </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>

djmysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Search{% endblock title %}

{% block content %}
  {% if "query" in request.GET %}
    <h1>Posts containing "{{ clean_data.query }}"</h1>
    <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>

    {% for result in results %}
      {% with post=result.object %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      {{ post.body|truncatewords:5 }}
      {% endwith %}
      {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}

    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form action="." method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}

{% endblock content %}

djmysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share post{% endblock title %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was sent to {{ cd.to }}.
      <a href="{{ post.get_absolute_url }}">Get back</a>
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by email</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send email">
    </form>
  {% endif %}
{% endblock content %}